print('Hello World!')
print('Hi')

print('       1')
print('     2 3')
print('   4 5 6')
print('7 8 9 10')

print('+---------------------------------------------------------------------+')
print('|                                                                     |')
print('|                                                                     |')
print('|        Wrote myself a letter                                        |')
print('|        just a single question                                       |')
print('|                                                                     |')
print('|        "When you finally get this, where will you be?" ✨           |')
print('|                                                                     |')
print('|        Will you be a shipwreck or a star                            |')
print('|        Falling for a boy who doesn\'t play guitar?                  |')
print('|        Now rewind the tape back to the start                        |')
print('|                                                                     |')
print('|                                          - Caroline Polachek        |')
print('|                                                                     |')
print('|                                                                     |')
print('+---------------------------------------------------------------------+')

# Snail Mail 💌
# Codédex

print('+---------------------------------------------------------------------------------+')
print('|                                                                                 |')
print('|                                                                 October 2025    |')
print('|                                                                 Brooklyn, NY    |')
print('|       Dear Self,                                                                |')
print('|                                                                                 |')
print('|       Does great art require suffering?                                         |')
print('|       Does great product demand capital?                                        |')
print('|       Did you find any truth at the end of the road?                            |')
print('|                                                                                 |')
print('|       Regardless, go build the learning platform you’ve always dreamed of —     |')
print('|       the one you wish existed when you first started.                          |')
print('|                                                                                 |')
print('|       Give more than you take.                                                  |')
print('|       Take only what you need.                                                  |')
print('|                                                                                 |')
print('|       And when things fall apart, get tf back up.                               |')
print('|                                                                                 |')
print('|       - Sonny Li                                                                |')
print('|                                                                                 |')
print('|       P.S. Hope I made you proud. You got this, kiddo. 🤠                       |')
print('|                                                                                 |')
print('+---------------------------------------------------------------------------------+')
